apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cluster: cluster-east
    owner: platform-team
  name: configsync-admin
  namespace: zoneprinter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: ns-reconciler-zoneprinter
  namespace: config-management-system
