apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: pubsub-sample
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/karlkfi/acm-examples-pubsub-sample
    revision: HEAD
    branch: main
    dir: "deploy/clusters/cluster-west/namespaces/pubsub-sample"
    auth: none
