apiVersion: configsync.gke.io/v1alpha1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: pubsub-sample
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/karlkfi/acm-examples-pubsub-sample
    revision: HEAD
    branch: main
    dir: "deploy/clusters/cluster-west/namespaces/pubsub-sample"
    auth: none
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: syncs-repo
  namespace: pubsub-sample
subjects:
- kind: ServiceAccount
  name: ns-reconciler-pubsub-sample
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
